rate1=float(input("rate1:"))
rate2=float(input("rate2:"))
rate3=float(input("rate3:"))
rate4=float(input("rate4:"))
rate5=float(input("rate5:"))
rate6=float(input("rate6:"))
growth_rate=[rate1,rate2,rate3,rate4,rate5,rate6]
growth_rate.sort()
print(growth_rate)
average = sum(growth_rate)/len(growth_rate)
print("average rate=", average)
lowest=min(growth_rate)
print("lowest rate=", lowest)
highest=max(growth_rate)
print("highest rate=", highest)