stu1=input("stu1:")
stu2=input("stu2:")
stu3=input("stu3:")
stu4=input("stu4:")
students=[stu1,stu2,stu3,stu4]
print(students)
stu5=input("stu5:")
students.append(stu5)
print(students)
remove_name=input("student to remove:")
students.remove(remove_name)
print(students)
total = len(students)
print("total students=", total)